apiVersion: v1
kind: Service
metadata:
  name: app-security-svc-lb
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30013
  selector:
    app: app-security-pod